# Generated by Django 5.2.7 on 2025-10-22 05:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField(default=0)),
                ('product_type', models.CharField(choices=[('CAKE', '🎂 Cakes'), ('CHOCOLATE', '🍫 Chocolates'), ('DRINK', '🥤 Soft Drinks')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_amount_inserted', models.IntegerField(default=0)),
                ('amount_required', models.IntegerField(default=0)),
                ('change_returned', models.IntegerField(default=0)),
                ('products_purchased', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DenominationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.IntegerField(choices=[(500, 'Rs 500'), (200, 'Rs 200'), (100, 'Rs 100'), (50, 'Rs 50'), (20, 'Rs 20'), (10, 'Rs 10'), (5, 'Rs 5')])),
                ('quantity_inserted', models.IntegerField(default=0)),
                ('quantity_returned', models.IntegerField(default=0)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='vending.transaction')),
            ],
        ),
    ]
